# Generated by Django 4.1.1 on 2022-10-03 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='finch',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='main_app.finch'),
        ),
    ]
