# Generated by Django 4.1.1 on 2022-10-03 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_picture_finch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='img',
            new_name='url',
        ),
    ]
